# Generated by Django 3.2.18 on 2023-10-08 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('userauths', '0002_alter_user_full_name_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
